export const FARMERS = [
    {
        id: "FR-001",
        name: "Lina Okoro",
        contact: "+254 712 345 678",
        email: "lina.okoro@agricentral.io",
        gender: "female",
        dob: "1988-04-12",
        address: "Plot 12, Kisumu Rd, Nairobi",
        status: "active",
        position: "president",
        farms: ["Greenfield Farm", "Sunrise Acres", "Riverbend Estate"],
        livestock: ["LS-001 · Cow #A-204"],
        equipment: ["EQ-002 · Harvester H-12"],
        history: [
            { kind: "livestock", action: "Received", item: "LS-001 · Cow #A-204", date: "2022-05-01" },
            { kind: "equipment", action: "Received", item: "EQ-002 · Harvester H-12", date: "2021-09-30" },
        ],
    },
    {
        id: "FR-002",
        name: "Samuel Mwangi",
        contact: "+254 700 112 233",
        email: "samuel.m@agricentral.io",
        gender: "male",
        dob: "1985-09-03",
        address: "Block B, Eldoret",
        status: "active",
        position: "president",
        farms: ["Highland Pastures", "Maple Hollow"],
        livestock: ["LS-002 · Goat #G-12"],
        equipment: ["EQ-001 · Tractor T-204"],
        history: [
            { kind: "equipment", action: "Received", item: "EQ-001 · Tractor T-204", date: "2022-04-12" },
            { kind: "livestock", action: "Received", item: "LS-002 · Goat #G-12", date: "2024-06-22" },
        ],
    },
    {
        id: "FR-003",
        name: "Aisha Bello",
        contact: "+234 802 555 0199",
        email: "aisha.bello@agricentral.io",
        gender: "female",
        dob: "1992-11-21",
        address: "Ikeja, Lagos",
        status: "inactive",
        position: "president",
        farms: ["Cedar Ridge"],
        livestock: ["LS-003 · Sheep #S-08"],
        equipment: [],
        history: [
            { kind: "livestock", action: "Received", item: "LS-003 · Sheep #S-08", date: "2023-01-15" },
            { kind: "equipment", action: "Returned", item: "EQ-003 · Plow P-08", date: "2024-02-09" },
        ],
    },
    {
        id: "FR-004",
        name: "Chidi Okafor",
        contact: "+234 813 222 7788",
        email: "chidi.o@agricentral.io",
        gender: "male",
        dob: "1979-02-17",
        address: "Enugu, Nigeria",
        status: "active",
        position: "president",
        farms: ["Willow Creek", "Goldenrod Plains", "Greenfield Farm"],
        livestock: ["LS-004 · Cow #A-117"],
        equipment: ["EQ-004 · Sprayer S-31"],
        history: [
            { kind: "livestock", action: "Received", item: "LS-004 · Cow #A-117", date: "2023-04-05" },
            { kind: "equipment", action: "Received", item: "EQ-004 · Sprayer S-31", date: "2023-01-20" },
        ],
    },
];

export const FARMS = [
    {
        id: "FM-001",
        address: "Brgy. Poblacion, Boac, Marinduque",
        size: 24,
        location: { lat: 13.4456, lng: 121.8403 },
        farmers: ["FR-001 · Lina Okoro", "FR-002 · Samuel Mwangi"],
        crops: [
            { crop: "Rice", status: "growing" },
            { crop: "Maize", status: "planted" },
            { crop: "Vegetables", status: "harvested" },
        ],
        yieldKg: 1250,
        history: [
            { action: "Received", item: "Rice seeds", date: "2024-02-10" },
            { action: "Harvested", item: "Vegetables", date: "2024-09-12" },
        ],
    },
    {
        id: "FM-002",
        address: "Brgy. Mataas na Bayan, Boac, Marinduque",
        size: 58,
        location: { lat: 13.4528, lng: 121.8352 },
        farmers: ["FR-004 · Chidi Okafor"],
        crops: [
            { crop: "Maize", status: "growing" },
            { crop: "Sorghum", status: "growing" },
        ],
        yieldKg: 3200,
        history: [
            { action: "Received", item: "Maize seeds", date: "2024-03-04" },
            { action: "Received", item: "Sorghum seeds", date: "2024-03-04" },
        ],
    },
    {
        id: "FM-003",
        address: "Brgy. Cawit, Boac, Marinduque",
        size: 12,
        location: { lat: 13.4302, lng: 121.8467 },
        farmers: ["FR-006 · Mariam Diallo"],
        crops: [
            { crop: "Vegetables", status: "harvested" },
            { crop: "Cassava", status: "growing" },
        ],
        yieldKg: 890,
        history: [
            { action: "Harvested", item: "Vegetables", date: "2024-08-19" },
        ],
    },
    {
        id: "FM-004",
        address: "Brgy. Tumagabok, Boac, Marinduque",
        size: 32,
        location: { lat: 13.4691, lng: 121.8688 },
        farmers: ["FR-003 · Aisha Bello", "FR-005 · Joseph Kamau"],
        crops: [{ crop: "Coffee", status: "growing" }],
        yieldKg: 0,
        history: [
            { action: "Received", item: "Coffee seedlings", date: "2023-11-20" },
        ],
    },
];

export const LIVESTOCKS = [
    {
        id: "LS-001",
        tag: "Cow #A-204",
        animal: "Cow",
        breed: "Friesian",
        gender: "female",
        dob: "2022-03-14",
        color: "Black & White",
        weight: 480,
        farmer: "Lina Okoro",
        health: "healthy",
        status: "active",
        acquisitionDate: "2022-05-01",
        history: [
            { farmer: "Lina Okoro", date: "2022-05-01" },
        ],
    },
    {
        id: "LS-002",
        tag: "Goat #G-12",
        animal: "Goat",
        breed: "Boer",
        gender: "male",
        dob: "2023-01-08",
        color: "Brown",
        weight: 52,
        farmer: "Samuel Mwangi",
        health: "observation",
        status: "active",
        acquisitionDate: "2023-02-10",
        history: [
            { farmer: "Joseph Kamau", date: "2023-02-10" },
            { farmer: "Samuel Mwangi", date: "2024-06-22" },
        ],
    },
    {
        id: "LS-003",
        tag: "Sheep #S-08",
        animal: "Sheep",
        breed: "Merino",
        gender: "female",
        dob: "2022-09-19",
        color: "White",
        weight: 64,
        farmer: "Aisha Bello",
        health: "sick",
        status: "quarantine",
        acquisitionDate: "2023-01-15",
        history: [{ farmer: "Aisha Bello", date: "2023-01-15" }],
    },
    {
        id: "LS-004",
        tag: "Cow #A-117",
        animal: "Cow",
        breed: "Jersey",
        gender: "female",
        dob: "2021-06-02",
        color: "Tan",
        weight: 420,
        farmer: "Chidi Okafor",
        health: "healthy",
        status: "active",
        acquisitionDate: "2021-08-20",
        history: [
            { farmer: "Grace Mensah", date: "2021-08-20" },
            { farmer: "Chidi Okafor", date: "2023-04-05" },
        ],
    },
];

export const EQUIPMENTS = [
    {
        id: "EQ-001",
        name: "Tractor T-204",
        condition: "excellent",
        status: "assigned",
        farmer: "Samuel Mwangi",
        acquisitionDate: "2022-04-12",
        history: [
            { name: "Tractor T-204", date: "2022-04-12" },
        ],
    },
    {
        id: "EQ-002",
        name: "Harvester H-12",
        condition: "good",
        status: "assigned",
        farmer: "Lina Okoro",
        acquisitionDate: "2021-09-30",
        history: [
            { name: "Harvester H-12", date: "2021-09-30" },
        ],
    },
    {
        id: "EQ-003",
        name: "Plow P-08",
        condition: "maintenance",
        status: "repair",
        farmer: "",
        acquisitionDate: "2020-06-15",
        history: [{ name: "Plow P-08", date: "2020-06-15" }],
    },
    {
        id: "EQ-004",
        name: "Sprayer S-31",
        condition: "good",
        status: "assigned",
        farmer: "Chidi Okafor",
        acquisitionDate: "2023-01-20",
        history: [{ name: "Sprayer S-31", date: "2023-01-20" }],
    },
];

export const REPORTS = [
    {
        id: "RP-001",
        title: "Maize leaf blight outbreak",
        type: "crop",
        reportedBy: "Lina Okoro",
        role: "far",
        severity: "high",
        status: "open",
        date: "2025-06-18",
        details: "Yellow-brown lesions spreading across the south plot. Affects approximately 1.2 hectares.",
    },
    {
        id: "RP-002",
        title: "Tractor hydraulic leak",
        type: "equipment",
        reportedBy: "Samuel Mwangi",
        role: "far",
        severity: "medium",
        status: "in_review",
        date: "2025-06-15",
        details: "John Deere 5055E losing hydraulic fluid from the front loader cylinder.",
    },
    {
        id: "RP-003",
        title: "Goat showing fever symptoms",
        type: "livestock",
        reportedBy: "Aisha Bello",
        role: "aew",
        severity: "critical",
        status: "open",
        date: "2025-06-20",
        details: "Goat #G-12 has elevated temperature and reduced feeding. Vet visit scheduled.",
    },
    {
        id: "RP-004",
        title: "Irrigation pump failure",
        type: "equipment",
        reportedBy: "Chidi Okafor",
        role: "aew",
        severity: "low",
        status: "resolved",
        date: "2025-05-30",
        details: "Pump motor replaced. System back online.",
    },
];

export const BOAC_CENTER = { lat: 13.4456, lng: 121.8403 };

export const CROP_OPTIONS = [
    "Rice",
    "Maize",
    "Wheat",
    "Vegetables",
    "Coffee",
    "Cocoa",
    "Cassava",
    "Sorghum",
];

export const CROP_STATUS_TONE = {
    planted: "info",
    growing: "success",
    harvested: "neutral",
    fallow: "warning",
};

export const CROP_STATUS_LABEL = {
    planted: "Planted",
    growing: "Growing",
    harvested: "Harvested",
    fallow: "Fallow",
};

export const USERS = [
    {
        id: "US-001",
        fullName: "Daniel Kiprotich",
        email: "daniel.kiprotich@agritrack.io",
        role: "far",
        isVerified: true,
    },
    {
        id: "US-002",
        fullName: "Lina Okoro",
        email: "lina.okoro@agritrack.io",
        role: "far",
        isVerified: true,
    },
    {
        id: "US-003",
        fullName: "Samuel Mwangi",
        email: "samuel.mwangi@agritrack.io",
        role: "aew",
        isVerified: true,
    },
    {
        id: "US-004",
        fullName: "Aisha Bello",
        email: "aisha.bello@agritrack.io",
        role: "aew",
        isVerified: true,
    },
    {
        id: "US-005",
        fullName: "Grace Mensah",
        email: "grace.mensah@agritrack.io",
        role: "coordinator",
        isVerified: true,
    },
    {
        id: "US-006",
        fullName: "Ibrahim Sow",
        email: "ibrahim.sow@agritrack.io",
        role: "coordinator",
        isVerified: true,
    },
    {
        id: "US-007",
        fullName: "Helen Adeyemi",
        email: "helen.adeyemi@agritrack.io",
        role: "governor",
        isVerified: true,
    },
    {
        id: "US-008",
        fullName: "Ravi Patel",
        email: "ravi.patel@agritrack.io",
        role: "head",
        isVerified: true,
    },
    // Example: a FAR who self-registered and is awaiting admin approval.
    {
        id: "US-009",
        fullName: "Wanjiru Kamau",
        email: "wanjiru.kamau@agritrack.io",
        role: "far",
        isVerified: false,
    },
];